# Generated by Django 4.1.7 on 2025-08-21 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Armed', 'Armed'), ('Unarmed', 'Unarmed'), ('Disarming', 'Disarming'), ('Compromised', 'Compromised')], default='Unarmed', max_length=20)),
                ('last_armed_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('pin_out', models.IntegerField()),
                ('pin_in', models.IntegerField()),
                ('state', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
            ],
        ),
    ]
