# Generated by Django 4.1.7 on 2023-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Armed', 'Armed'), ('Unarmed', 'Unarmed')], default='Unarmed', max_length=20)),
            ],
        ),
    ]
