# Generated by Django 4.1.7 on 2023-02-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_armstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armstatus',
            name='state',
            field=models.CharField(choices=[('Armed', 'Armed'), ('Unarmed', 'Unarmed'), ('Disarming', 'Disarming'), ('Compromised', 'Compromised')], default='Unarmed', max_length=20),
        ),
    ]
